//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generarBoleta
{
    using System;
    using System.Collections.Generic;
    
    public partial class automoviles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public automoviles()
        {
            this.boleta = new HashSet<boleta>();
        }
    
        public int carros_id { get; set; }
        public string placa { get; set; }
        public string descripcion { get; set; }
        public string propietario { get; set; }
        public Nullable<int> tipo_carro_id { get; set; }
    
        public virtual tipo_automoviles tipo_automoviles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boleta> boleta { get; set; }
    }
}
