//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generarBoleta
{
    using System;
    using System.Collections.Generic;
    
    public partial class boleta
    {
        public int botela_id { get; set; }
        public Nullable<int> parkingLot_id { get; set; }
        public Nullable<int> usuarios_id { get; set; }
        public Nullable<int> carros_id { get; set; }
        public Nullable<System.DateTime> inicioHora { get; set; }
        public Nullable<System.DateTime> finalHora { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<double> descuento { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual automoviles automoviles { get; set; }
        public virtual parkingLot parkingLot { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
