//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generarBoleta
{
    using System;
    using System.Collections.Generic;
    
    public partial class parkingLot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public parkingLot()
        {
            this.boleta = new HashSet<boleta>();
        }
    
        public int parkingLot_id { get; set; }
        public Nullable<int> usuarios_id { get; set; }
        public string nombre_local { get; set; }
        public string ubicacion { get; set; }
        public Nullable<double> cobroHora { get; set; }
        public Nullable<int> lugares { get; set; }
        public Nullable<double> saldo { get; set; }
        public Nullable<int> coches_actuales { get; set; }
        public Nullable<int> Pago_realizado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boleta> boleta { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
